name: VideoParticlePlayer
version: '2.0'
main: top.yzljc.playVideo.PlayVideo
api-version: '1.21'
authors: [yz-ljc]
description: Plays videos using particles with color support
commands:
  playvideo:
    description: Control the video playback
    aliases: [pv]
    usage: /playvideo <load|play|stop> [filename]
    permission: playvideo.use